// export 'ajuan_detail_page.dart';
// export 'ajuan_tunjangan_page.dart';
// export 'approval_pengajuan_page.dart';
// export 'attendance_for_atasan_page.dart';
// export 'attendance_page.dart';
// export 'attendance_period_page.dart';
// export 'camera_page.dart';
// export 'change_password_page.dart';
// export 'check_in_page.dart';
// export 'contract_approve_page.dart';
// export 'contract_detail_page.dart';
// export 'contract_preview_page.dart';
// export 'coverage_area/coverage_area.dart';
// export 'distributor_page.dart';
// export 'fpk_detail_candidate_page.dart';
// export 'fpk_detail_page.dart';
// export 'fpk_input_candidate_page.dart';
// export 'fpk_request_page.dart';
// export 'hirarki_page.dart';
// export 'history_ajuan_page.dart';
// export 'history_approval_page.dart';
// export 'history_contract_employee_page.dart';
// export 'history_contract_page.dart';
// export 'history_fpk_page.dart';
// export 'history_idcard_page.dart';
export 'home_page.dart';
// export 'idcard_page.dart';
// export 'input_approval_page.dart';
// export 'insurance_page.dart';
// export 'latesoon_attendance_page.dart';
export 'layout.dart';
// export 'leave_request_page.dart';
// export 'list_approval_page.dart';
export 'login.dart';
// export 'message_tab_page.dart';
// export 'news_detail_page.dart';
// export 'news_page.dart';
export 'notfound_page.dart';
export 'onboarding.dart';
// export 'pdf_viewer_page.dart';
// export 'pending_ajuan_page.dart';
// export 'pending_contract_page.dart';
// export 'pending_fpk_page.dart';
// export 'pengajuan_idcard_page.dart';
// export 'pengajuan_lembur_page.dart';
// export 'pengajuan_page.dart';
// export 'perbaikan_absen_page.dart';
// export 'profile_home_page.dart';
// export 'profile_page.dart';
// export 'report_hk_page.dart';
// export 'search_employee_page.dart';
// export 'set_schedule_filter_page.dart';
export 'setting_page.dart';
// export 'sisa_cuti_detail_page.dart';
export 'splash.dart';
// export 'tukar_libur_page.dart';
// export 'tunjangan/tunjangan.dart';
// export 'update_profile_page.dart';
export 'webview_page.dart';
